Contributions summary script
StevensSEC/scripts pull request #2
Opened 2021-01-03 16:19 UTC by carpenterd777

Fixes #1

2021-01-03 16:22 UTC, dyc3 commented
Can you add a README.md in the same folder as the script describing what this does and how to use it?

2021-01-06 17:47 UTC, dyc3 requested changes
It's a good first draft, thanks for putting it together.

I think it would be better if we could allow it to take command line arguments instead of prompting. Maybe the prompt could appear only if no arguments were provided. This way, we could easily automate adding the report to the website at the end of each semester.

Make the output of the script either:
A: json, or some other machine readable format
B: something we can copy/paste directly into a markdown file for the website

2021-01-06 17:47 UTC, dyc3 commented on contributions/__main__.py
> +"""Download metadata for all StevensSEC projects"""
Let's change all these to `#` comments, and reserve `"""` for python docstrings.

2021-01-06 17:47 UTC, dyc3 commented on contributions/__main__.py
> +columns = [column for column in columns if "Pull request" in column.name]
Slightly more robust:
```suggestion
columns = [column for column in columns if "pull request" in column.name.lower()]
```

2021-01-06 17:47 UTC, dyc3 commented on contributions/__main__.py
> +        pull_requests.append(match.group())
Not necessary, but if we want to require python 3.8+
```suggestion
    if match := re.search(r"https://github.com/(\w|\d)+/(\w|\d)+/(pull|issues)/\d+", note):
        pull_requests.append(match.group())
```

2021-01-08 02:10 UTC, carpenterd777 commented
I've made the changes as requested, and edited the script to only display the prompt if no arguments are provided. The script takes the name of the contributions board as an argument, and prints a JSON with the contributors and the referenced issues.

I made it so that if the user uses the prompt to get a summary, the script makes a new file called `output.json` with the summary. I mostly made this change because if the user tries to redirect the output into a file the prompt is put there which might be confusing/frustrating. What do you think?

2021-01-15 21:01 UTC, merged